CREATE TABLE [config].[CHECK_EXTRACTION_STATUS] (
    [MODEL_NAME]         NVARCHAR (255) NOT NULL,
    [PERIODICITY]        NVARCHAR (255) NULL,
    [DT_START_EXECUTION] DATETIME       NULL,
    [DT_END_EXECUTION]   DATETIME       NULL,
    [FLG_SUCCESS]        BIT            NULL,
    [PIPELINE_ID]        NVARCHAR (255) NOT NULL,
    [DT_CREATED]         DATETIME       DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]         NVARCHAR (255) DEFAULT ((1)) NOT NULL,
    [DT_MODIFIED]        DATETIME       DEFAULT (getdate()) NOT NULL,
    [MODIFIED_BY]        NVARCHAR (255) DEFAULT ((1)) NOT NULL
);

