CREATE TABLE [config].[CONFIG_GROUP_DEPENDENCY] (
    [PK_GROUP_DEPENDENCY]   INT            NOT NULL,
    [MODEL_NAME]            NVARCHAR (255) NOT NULL,
    [GROUP_NAME]            NVARCHAR (255) NOT NULL,
    [DEPENDENCY_MODEL_NAME] NVARCHAR (255) NULL,
    [DEPENDENCY_GROUP_NAME] NVARCHAR (255) NULL,
    [DT_CREATED]            DATETIME       DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]            NVARCHAR (255) DEFAULT ((1)) NOT NULL,
    [DT_MODIFIED]           DATETIME       DEFAULT (getdate()) NOT NULL,
    [MODIFIED_BY]           NVARCHAR (255) DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([PK_GROUP_DEPENDENCY] ASC)
);

